=== AlienorD/InspecteurDeryque/Divers/REST/resume.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="resume">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="name" type="xs:string" />
      <xs:element name="desc" type="xs:string" />
      <xs:element name="count" type="xs:string" />
      <xs:element name="start_t" type="xs:string" />
      <xs:element name="end_t" type="xs:string" />
      
      <xs:element name="format">
        <xs:complexType>
          <xs:sequence>
          
            <xs:element name="datatype" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="dataname" type="xs:string" />
                  <xs:element name="label" type="xs:string" />
                  <xs:element name="unit" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      
      <xs:element name="mod" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== AlienorD/InspecteurDeryque/Divers/REST/resume1.xml
<?xml version="1.0" encoding="UTF-8"?>
<resume xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resume.xsd">
	<name>canard</name>
	<desc>c'est la danse</desc>
	<count>42</count>
	<start_t>1997−07−16T19:20:30,4+01:00</start_t>
	<end_t>aaaa−mm−qqThh:mi:ss,nzzzzzz</end_t>
	<format>
		<datatype>
			<dataname>lat</dataname>
			<label>lattitude</label>
			<unit>degree</unit>
		</datatype>
		<datatype>
			<dataname>lon</dataname>
			<label>longitude</label>
			<unit>degree</unit>
		</datatype>
	</format>
	<mod>average</mod>
	<mod>derivative</mod>
</resume>
